server:
  port: 8089
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com

info:
  app:
    name: Spring Sample Application
    description: This is my first spring boot application
    version: 1.0.0
#actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,beans